function ht = pd_text(x, y, str, varargin)
%PD_TEXT Free text with the diagram's typography.
%   pd_text(x, y, 'Annotation')
%   pd_text(x, y, '(a)', 'FontWeight','bold', 'HA','left', 'VA','top')
%   pd_text(x, y, '$\dot{m}_{\mathrm{feed}}$', 'Interpreter','latex')
%   Options: 'FontSize','FontWeight','FontAngle','Color','HA','VA',
%            'Rotation','Interpreter','Background'
S = pd_getstyle();
o = pd_opts(struct('FontSize', S.fontSize, 'FontWeight', 'normal', ...
    'FontAngle', 'normal', 'Color', S.textColor, 'HA', 'center', ...
    'VA', 'middle', 'Rotation', 0, 'Interpreter', S.interpreter, ...
    'Background', 'none', 'Parent', gca), varargin{:});
ht = text(x, y, str, 'Parent', o.Parent, 'FontName', S.font, ...
    'FontSize', o.FontSize, 'FontWeight', o.FontWeight, 'FontAngle', o.FontAngle, ...
    'Color', o.Color, 'HorizontalAlignment', o.HA, 'VerticalAlignment', o.VA, ...
    'Rotation', o.Rotation, 'Interpreter', o.Interpreter, ...
    'BackgroundColor', o.Background, 'Margin', 0.5, 'Tag', 'pd_text');
end
